var M=null;
(function(p){function k(g,e,v,k){function p(e){-1<l.indexOf(e)||(l.push(e),v&&v(e,l.length),l.length===g.length&&k&&k())}for(var l=[],A=0;A<g.length;A++)g[A].url&&r(g[A].type,g[A].url,e,p)}function r(g,e,k,l){function p(e){var g=document.createElement(e.element),k;for(k in e)"element"!==k&&"appendTo"!==k&&(g[k]=e[k]);return"object"===typeof document.getElementsByTagName(e.appendTo)[0].appendChild(g)}function v(e){var g=p({element:"link",rel:"stylesheet",type:"text/css",href:e,onload:x.bind(this,e),
appendTo:"head"}),k=setInterval(function(){for(var g=document.styleSheets,l=0;l<g.length;l++)g[l].href&&g[l].href.substr(g[l].href.indexOf(e),g[l].href.length)===e&&(clearInterval(k),x(e))},500);return g}function r(e){return p({element:"script",type:"text/javascript",onload:x.bind(this,e),onreadystatechange:D.bind(this,e),src:e,appendTo:"body"})}function x(e){l&&l(e)}function D(e){"loaded"!==this.readyState&&"complete"!==this.readyState||x(e)}k&&k(g);"css"===g?v(e):r(e)}function R(g,e){l=window.XMLHttpRequest?
new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");l.onreadystatechange=e;l.open("GET",g,!0);l.setRequestHeader("Content-type","application/x-www-form-urlencoded");l.send()}function F(g){switch(g.apiOptions.platform){case "openlayer":break;default:mapApi4ArgsInit(g)}}location.pathname.replace(/\/[^/]*$/,"");Array.prototype.indexOf||(Array.prototype.indexOf=function(g,e){var k=this.length>>>0;e=Number(e)||0;e=0>e?Math.ceil(e):Math.floor(e);for(0>e&&(e+=k);e<k;e++)if(e in this&&this[e]===g)return e;
return-1});String.prototype.trim||(String.prototype.trim=function(){return this.replace(/(^\s*)|(\s*$)/g,"")});p.loadResources=k;p.loadResource=r;var l,y=function(){var g=document.getElementById("mapApi"),e=null;if(g)try{e=JSON.parse(g.getAttribute("data-options"))}catch(v){console.error(v),console.error("\u89e3\u6790data-options\u51fa\u9519\uff01")}return e}(),D=function(){var g=document.getElementById("mapApi");return g&&(g=g.getAttribute("data-config"))?g:"config.json"}();D&&(console.time("\u52a0\u8f7d\u914d\u7f6e\u6587\u4ef6"),
R(D,function(){l=arguments[0]&&arguments[0].target?arguments[0].target:arguments.caller;if(4==l.readyState&&200==l.status){console.timeEnd("\u52a0\u8f7d\u914d\u7f6e\u6587\u4ef6");var g={};try{var e=JSON.parse(l.responseText);g=y.appName?e[y.appName]:e;g.apiOptions=y;g.resources&&0<g.resources.length?(console.time("\u52a0\u8f7darcgis for js\u5fc5\u8981\u7684\u8d44\u6e90"),k(g.resources,function(e){"dojo"===e&&g.dojoConfig&&(p.dojoConfig=g.dojoConfig)},null,function(){console.timeEnd("\u52a0\u8f7darcgis for js\u5fc5\u8981\u7684\u8d44\u6e90");
F(g)})):F(g)}catch(v){console.error(v),console.error("\u5730\u56fe\u914d\u7f6e\u6587\u4ef6\u89e3\u6790\u51fa\u9519\uff0c\u8bf7\u68c0\u67e5\uff01")}}}))})(window);
function mapApi4ArgsInit(p){require("dojo/_base/lang dojo/_base/array dojo/Deferred dojo/promise/all dojo/_base/event dojo/dom-construct dojo/topic esri/urlUtils esri/tasks/GeometryService esri/tasks/LengthsParameters esri/tasks/AreasAndLengthsParameters esri/basemaps esri/map esri/geometry/Extent esri/geometry/Point esri/geometry/Circle esri/InfoTemplate esri/graphic esri/graphicsUtils esri/geometry/screenUtils esri/geometry/webMercatorUtils esri/layers/ArcGISTiledMapServiceLayer esri/layers/ArcGISDynamicMapServiceLayer esri/layers/FeatureLayer esri/layers/GraphicsLayer esri/layers/VectorTileLayer esri/renderers/SimpleRenderer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/PictureMarkerSymbol esri/symbols/SimpleFillSymbol esri/symbols/TextSymbol esri/symbols/Font esri/Color esri/geometry/jsonUtils esri/toolbars/navigation esri/toolbars/draw esri/toolbars/edit esri/geometry/geometryEngine esri/tasks/PrintTask esri/tasks/PrintParameters esri/dijit/Scalebar esri/dijit/InfoWindow extras/FlashFeatureLayer extras/DrawLayer extras/TiandituLayer extras/PipelineLayer dojo/domReady!".split(" "),function(k,
r,R,F,l,y,D,g,e,v,ta,Oa,ua,A,x,wa,va,E,ha,Pa,ia,xa,ya,za,Aa,Ba,S,L,T,X,N,Y,B,ja,ka,G,z,Ca,Qa,Da,Ea,Fa,Ra,Ga,Ha,Ia,Ja){M=function(g){var y={drawLayerId:"drawAndEditLayerId",zoomLevel:3,geometryService:"https://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer",printService:"https://sampleserver6.arcgisonline.com/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task"},H={ErrorEvent:"ErrorEvent",MapLoadedEvent:"MapLoadedEvent",InfoWindowShow:"InfoWindowShow",
InfoWindowHide:"InfoWindowHide",BaseMapLayersLoaded:"BaseMapLayersLoaded",OptionalLayersLoaded:"OptionalLayersLoaded",OptionalLayerAddedEvent:"OptionalLayerAddedEvent",OptionalLayersChangedEvent:"OptionalLayersChangedEvent"},n={apiLoading:"api\u521d\u59cb\u5316",mapLoading:"\u5730\u56fe\u521d\u59cb\u5316",createLayerError:"\u56fe\u5c42\u521b\u5efa\u5931\u8d25\uff0c\u8bf7\u68c0\u67e5\u914d\u7f6e\uff01",hasNoLayerTypeError:"\u65e0\u6cd5\u521b\u5efa\u7684\u56fe\u5c42\u7c7b\u578b",layerNotLoaded:"\u8be5\u56fe\u5c42\u672a\u52a0\u8f7d \uff0clayerId=",
layerUrlNotNull:"\u8be5\u7c7b\u578b\u56fe\u5c42url\u4e0d\u80fd\u4e3a\u7a7a \uff0clayerId=",eventNotRegister:"\u4e8b\u4ef6\u6ca1\u6709\u6ce8\u518c\uff0c\u56de\u8c03\u51fd\u6570\u65e0\u6cd5\u6267\u884c\uff01type=",graphicCreateError:"\u56fe\u5f62\u521b\u5efa\u51fa\u9519 \uff0c\u8bf7\u68c0\u67e5\u6570\u636e\u7ed3\u6784",getDistanceError:"\u8ba1\u7b97\u8ddd\u79bb\u51fa\u9519\uff01",getAreaError:"\u8ba1\u7b97\u9762\u79ef\u51fa\u9519\uff01",invalidFlashData:"\u65e0\u6548\u7684\u95ea\u70c1\u89c4\u5219",
featureNotFound:"\u6ca1\u6709\u67e5\u8be2\u5230\u76ee\u6807",queryError:"\u67e5\u8be2\u51fa\u9519",layerSetNotFound:"\u6ca1\u6709\u627e\u5230\u5bf9\u5e94\u7684id",repeatIdError:"\u91cd\u590dID"},m=new function(){this.log=function(a){console.log(a)};this.publishInfo=function(a){a&&console.log(a);c.publish(H.ErrorEvent,{message:a,type:"info"})};this.publishError=function(a,b){b&&console.error(b);a&&console.error(a);c.publish(H.ErrorEvent,{message:a,type:"error"})};this.publishEvent=function(){c.publish.apply(c,
arguments)}},F={getDefaultSymbolByGeoType:function(a){var b=null;switch(a){case "point":case "multipoint":b={color:[255,0,255,255],size:10,angle:0,xoffset:0,yoffset:0,type:"esriSMS",style:"esriSMSCircle",outline:{color:[255,0,255,255],width:0,type:"esriSLS",style:"esriSLSSolid"}};break;case "polyline":b={type:"esriSLS",style:"esriSLSSolid",color:[255,0,255,255],width:2};break;case "polygon":b={type:"esriSFS",style:"esriSFSSolid",color:[115,76,45,100],outline:{type:"esriSLS",style:"esriSLSSolid",color:[255,
0,255,255],width:2}}}c.getSymbolByObject(b)},getDefaultHighlightSymbol:function(a,b){b=a.geometry.type;a=a.symbol?a.symbol:F.getDefaultSymbolByGeoType(b);b=k.clone(a);switch(a.type){case "simplemarkersymbol":b.setSize(a.size+2);break;case "picturemarkersymbol":b.setHeight(1.5*a.height);b.setWidth(1.5*a.width);break;case "simplelinesymbol":b.setWidth(a.width+3);b.setColor(obj.color);b.setStyle(obj.style);break;case "picturefillsymbol":case "simplefillsymbol":b=new N(this._hightlightSymbols.simpleFillSymbol),
b.outline.setWidth(a.outline.width+3)}return b}},R={findGraphicsByAttributes:function(a,b){for(var c=[],f=0;f<a.length;f++){var q=a[f],h=q.attributes,e=!0,g;for(g in b)if(b[g]!==h[g]){e=!1;break}e&&c.push(q)}return c}};new function(){};var c=this,la=null,I=null,U=[],ma=[],C=null,na=[],oa=null,Z=null,pa=null,t=null,Ka=function(){var a=k.mixin({},{sliderStyle:"large",logo:!1,showAttribution:!1,showLabels:!0},oa);a.extent&&(a.extent=new A(a.extent));c.map||(c.map=new ua(la,a));c.map.on("load",function(a){console.timeEnd(n.mapLoading);
m.publishEvent(c.Events.MapLoadedEvent,a)});c.map.on("layer-add",function(a){var b=a.layer;b._attrs&&!b._attrs.baseLayer&&m.publishEvent(c.Events.OptionalLayerAddedEvent,a)});c.map.infoWindow.on("selection-change",function(a){m.publishEvent(c.Events.InfoWindowShow,a)});c.map.infoWindow.on("hide",function(a){m.publishEvent(c.Events.InfoWindowHide,a)})},V=function(a,b,c){b&&"function"===typeof b&&b(a,c);if(a.layerSet&&0<a.layerSet.length){c=a.layerSet;for(var d=0;d<c.length;d++)V(c[d],b,a)}},La=function(a){var b=
[],d=[],f=a.length;if(0!==f){for(var q=0;q<f;q++){var h=a[q];h={id:h.id,url:h.url,index:h.index?h.index:0,label:h.label,type:h.type,spatialReference:h.spatialReference,visible:void 0===h.visible||!1!==h.visible?!0:!1,attributes:{baseLayer:!0}};U.push(h);!1===h.visible?d.push(h):b.push(h)}a=b.length;0===a&&(d[0].visible=!0);if(1<a)for(q=1;q<a;q++)b[q].visible=!1;b=[].concat(b,d);r.forEach(b,function(a,b){b=O(a);c.map.addLayer(b,a.index)})}},qa=function(a){r.forEach(a,function(a,b){V(a,function(a,b){a.layerSet?
b&&(void 0!==b.type&&(a.type=b.type),!1===b.visible&&(a.visible=!1)):(b&&!1===b.visible&&(a.visible=!1),b&&"GeoBaseData"===b.type&&na.push(a),ma.push(a))})});var b=[].concat(ma,na);r.forEach(b,function(a,b){void 0==a.index&&(a.index=30)});b.sort(function(a,b){return a.index-b.index});r.forEach(b,function(a){var b={id:a.id,url:a.url,type:a.type,visible:1==a.visible||void 0==a.visible,outFields:["*"],showLabels:!0};a.renderer&&(b.renderer=a.renderer);(a=O(b))&&c.map.addLayer(a)});m.publishEvent(H.OptionalLayersChangedEvent,
b,a)},O=function(a){a=k.clone(a);a.id&&(a.id=a.id.toUpperCase());var b=null,d=a.type,f=a.url?a.url.trim():null;delete a.type;delete a.url;try{if(!(f&&""!==f||"tile"!==d&&"feature"!==d&&"flash"!==d&&"dynamic"!==d)){m.log(n.layerUrlNotNull+a.id);return}switch(d){case "tile":b=new xa(f,a);break;case "feature":b=new za(f,a);break;case "flash":a.outFields=a.outFields?a.outFields:["*"];b=new Ga(f,a,c);break;case "dynamic":b=new ya(f,a);break;case "graphic":b=new Aa(a);break;case "draw":b=new Ha(a);break;
case "tdt-vec":case "tdt-cva":case "tdt-ter":case "tdt-cta":case "tdt-img":case "tdt-cia":b=new Ia(f,a);break;case "vector-tile":b=new Ba(f,a);break;case "pipeline":b=new Ja({id:a.id,visible:a.visible,url:f,renderer:a.renderer});break;default:m.log(n.hasNoLayerTypeError+" type="+d)}}catch(q){m.log(n.createLayerError,q)}return b},J=function(a){a&&a.remove();return null},Ma=function(a,b){var d=new Ea;d.map=c.map;pa.execute(d,a,b)},W=function(a,b){a&&"function"===typeof a&&a(b)};c.apiConfig=p;c.Events=
H;c.Strings=n;c.map=null;c.startup=function(){console.time(n.mapLoading);I&&I.baseMapLayers&&0<I.baseMapLayers.length&&(La(I.baseMapLayers),m.publishEvent(c.Events.BaseMapLayersLoaded,I.baseMapLayers));C&&0<C.length&&(qa(C),m.publishEvent(c.Events.OptionalLayersLoaded,C));return c};c.startPanMode=function(){ra();c.map.showZoomSlider();c.map.setMapCursor("default");null==t&&(t=new G(c.map));t.deactivate();t.activate(G.PAN);c.map.setMapCursor("pointer")};c.centerAt=function(a,b){a=parseFloat(a);b=parseFloat(b);
return c.map.centerAt(new x(a,b,c.map.spatialReference))};c.setLevel=function(a){c.map.setLevel(a)};c.levelUp=function(){var a=c.map.getLevel();c.map.setLevel(++a)};c.levelDown=function(){var a=c.map.getLevel();c.map.setLevel(--a)};c.zoomIn=function(){null==t&&(t=new G(c.map));t.deactivate();c.map.setMapCursor("default");t.activate(G.ZOOM_IN)};c.zoomOut=function(){null==t&&(t=new G(c.map));t.deactivate();c.map.setMapCursor("default");t.activate(G.ZOOM_OUT)};c.zoomAt=function(a,b,d){b=parseFloat(b);
d=parseFloat(d);c.map.centerAndZoom(new x(b,d,c.map.spatialReference),a?a:y.level)};c.zoomGeometrys=function(a,b){a=ka.fromJson(a);a=c.getCenter(a);c.map.centerAndZoom(a,b?b:y.level)};c.zoomLayer=function(a){if(a=c.getLayerById(a))a.minScale?c.map.setScale(a.minScale):(a=ha.graphicsExtent(a.graphics),c.map.setExtent(a))};c.zoomExtent=function(a,b,d,f){a=new A(a,b,d,f,c.map.spatialReference);c.map.setExtent(a)};c.hideZoomSlider=function(a){a?c.map.hideZoomSlider():c.map.showZoomSlider()};c.createGraphicLayer=
function(a,b){b=b?b:{};b.id=a;b.type="graphic";a=O(b);c.map.addLayer(a);return a};c.addGraphics=function(a,b){var d=c.getLayerById(a);try{d||(d=c.map.graphics);for(var f=0;f<b.length;f++){var q=new E(b[f]);d.add(q)}return}catch(h){m.publishError(n.graphicCreateError,h)}m.publishInfo(n.layerNotLoaded+a)};c.removeGraphics=function(a){var b=k.mixin({},{layerId:null,attributes:null},a),d=[];a=null==b.layerId?c.map.graphics:c.getLayerById(b.layerId);if(b.attributes){for(var f=0;f<a.graphics.length;f++){var q=
a.graphics[f],h=q.attributes,e=!0;if(h&&"object"===typeof h){for(var g in b.attributes)if(h[g]!==b.attributes[g]){e=!1;break}e&&d.push(q)}}for(g=0;g<d.length;g++)a.remove(d[g])}};c.removeLayerByIds=function(a){r.forEach(a,function(a){(a=c.getLayerById(a))&&c.map.removeLayer(a)})};c.refreshLayerById=function(a){(a=c.getLayerById(a))&&a.redraw()};c.removeAllLayers=function(){c.map.removeAllLayers()};c.layerVisibleSwitch=function(a,b){var d=c.getLayerById(a);if(d)return d.setVisibility(b),d;m.log(n.layerNotLoaded+
a)};c.clearGraphicsLayer=function(a){(a=c.getLayerById(a))&&a.clear()};c.clearMapGraphics=function(){var a=c.map.graphics;a&&a.clear()};c.setPointLayerRenderer=function(a,b){b=k.mixin({color:[255,255,255,64],size:12,angle:-30,xoffset:0,yoffset:0,type:"esriSMS",style:"esriSMSCircle",outline:{color:[0,0,0,255],width:1,type:"esriSLS",style:"esriSLSSolid"}},b);a=c.getLayerById(a);b=new L(b);b=new S(b);a.setRenderer(b)};c.setPointLayerPictureRenderer=function(a,b){b=k.mixin({url:"images/point.png",height:20,
width:20,type:"esriPMS",angle:0},b);a=c.getLayerById(a);b=new X(b);b=new S(b);a.setRenderer(b)};c.setLineLayerRenderer=function(a,b){b=k.mixin({type:"esriSLS",style:"esriSLSDot",color:[115,76,0,255],width:1},b);a=c.getLayerById(a);b=new T(b);b=new S(b);a.setRenderer(b)};c.setPolygonLayerRenderer=function(a,b){b=k.mixin({type:"esriSFS",style:"esriSFSSolid",color:[115,76,0,255],outline:{type:"esriSLS",style:"esriSLSSolid",color:[110,110,110,255],width:1}},b);a=c.getLayerById(a);b=new N(b);b=new S(b);
a.setRenderer(b)};c.setLayerOpacity=function(a,b){(a=c.getLayerById(a))&&a.setOpacity(b)};c.getSymbolByObject=function(a){var b=null;switch(a.type){case "esriSMS":b=new L(a);break;case "esriSLS":b=new T(a);break;case "esriSFS":b=new N(a);break;case "esriPMS":b=new X(a);break;case "esriTS":b=new Y(a)}return b};c.setLayerInfoWindow=function(a,b,d){if(a=c.getLayerById(a))a.infoTemplate=new va(b,d)};c.getLayerVisible=function(a){return(a=c.getLayerById(a))?a.visible:!1};c.getMapLevel=function(){return c.map.getLevel()};
c.getMapMaxLevel=function(){return c.map.getMaxZoom()};c.getXY=function(a){if("function"===typeof a){var b=c.map.cursor;"crosshair"!==b&&c.map.setMapCursor("crosshair");var d=c.map.on("click",function(f){d.remove();c.map.setMapCursor(b);a(f.mapPoint.x+","+f.mapPoint.y)})}};c.getLayerById=function(a){a=a.toUpperCase();if(a=c.map.getLayer(a))return a};c.getMapCenter=function(){return c.map.extent.getCenter()};c.getMapExtent=function(){return c.map.extent};c.getCircle=function(a,b,c){a=new wa(a,{radius:b});
b=[];for(var d=a.rings.length,e=0;e<d.length;e++)for(var h=0;h<c;h++)b.push(a.getPoint(e,h));return b};c.getCenterLocation=function(a){a=ka.fromJson(a);return c.getCenter(a)};c.getCenter=function(a){var b=null;switch(a.type){case "point":b=a;break;case "mutilpoint":case "polyline":case "polygon":b=a.getExtent().getCenter();break;case "extent":b=a.getCenter()}return b};c.addMapLoadedEventListener=function(a){return c.map.on("load",a)};c.addZoomEventListener=function(a){return c.map.on("zoom",a)};c.addExtentEventListener=
function(a){return c.map.on("extent-change",a)};c.addMouseMoveEventListener=function(a){return c.map.on("mouse-move",a)};c.addLayerClickEventListener=function(a,b){var d=c.getLayerById(a);if(d)return d.on("click",b);m.publishInfo(n.layerNotLoaded+a)};c.addLayerVisibilityChangeEventListener=function(a,b){var d=c.getLayerById(a);if(d)return d.on("visibility-change",b);m.publishInfo(n.layerNotLoaded+a)};c.removeEventListener=function(a){a&&a.remove()};c.addPictureGraphic=function(a,b,d){d=k.mixin({},
{url:"images/location.png",width:24,height:24,attributes:null,layerId:null},d);a=new x(a,b,c.map.spatialReference);b=new X(d);b=new E(a,b);d.layerId&&""!==d.layerId?(a=c.getLayerById(d.layerId),a||(a=O({id:d.layerId,type:"graphic"}),c.map.addLayer(a))):a=c.map.graphics;d.attributes&&b.setAttributes(d.attributes);a.add(b)};c.flashPoints=function(a,b,c,f){};c.flashGraphic=function(a,b,d){var f=k.mixin({},{repeatCount:5,delay:500,fieldName:"OBJECTID",center:!0,scale:2E4},d),e=null,h=!0,g=[];b=b.toUpperCase();
(d=c.getLayerById(b))?d&&0==d.visible&&d.setVisibility(!0):-1<c.map.graphicsLayerIds.indexOf(b)&&(d=c.map._layers[b],d.setVisibility(!0));if(d)if(d.flash&&"function"===typeof d.flash)d.flash(a,f);else{var l=function(a,b){for(var c=0;c<a.length;c++){var d=a[c];d._beforeSymbol||(d._beforeSymbol=d.symbol);d._highlightSymbol||(d._highlightSymbol=F.getDefaultHighlightSymbol(d));d.setSymbol(b?d._highlightSymbol:d._beforeSymbol)}};b=function(a){if(!0===f.center){var b=ha.graphicsExtent(a);c.map.setExtent(b)}var d=
f.repeatCount;e=setInterval(function(){0<d?(h?(d--,l(a,!0)):l(a,!1),h=!h):(clearInterval(e),l(a,!1))},f.delay)};"object"===typeof a&&a.geometry?g.push(a):"object"!==typeof a&&""!==f.fieldName&&(g={},g[f.fieldName]=a,g=R.findGraphicsByAttributes(d.graphics,g));0<g.length?b(g):m.publishInfo(n.invalidFlashData)}else m.publishInfo(n.layerNotLoaded+b)};c.drawGraphic=function(a,b,d){var f=[255,100,0];u=new z(c.map);K&&K.remove();t&&t.deactivate();K=u.on("draw-end",function(b){u.deactivate();c.map.showZoomSlider();
c.map.setMapCursor("default");switch(b.geometry.type){case "point":case "multipoint":var h=new L;h.setColor(f);break;case "polyline":h=new T;h.setColor(f);h.setWidth(2);break;case "polygon":h=new N,h.outline.setColor(f),h.outline.setWidth(2)}b=new E(b.geometry,h);b.attributes||(b.attributes={});a&&(b.attributes.id=a);h=b.geometry;h=3857==h.spatialReference.wkid||102100==h.spatialReference.wkid?ia.webMercatorToGeographic(h):h;W(d,h);c.map.graphics.add(b)});u.activate(b);c.map.hideZoomSlider();c.map.setMapCursor("crosshair")};
c.drawCircle=function(a,b){c.drawGraphic(a,z.CIRCLE,b)};c.drawLine=function(a,b){c.drawGraphic(a,z.LINE,b)};c.drawPolygon=function(a,b){c.drawGraphic(a,z.POLYGON,b)};c.drawPolyline=function(a,b){c.drawGraphic(a,z.POLYLINE,b)};c.drawLineAndGetLength=function(a,b){var d=[255,200,0];c.drawGraphic(a,z.POLYLINE,function(a){if(a){var f=new v;f.polylines=[a];f.lengthUnit=e.UNIT_METER;f.geodesic=!0;Z.lengths(f,function(f){W(b,f.lengths[0]);var e=a.paths[0];e=e[e.length-1];e=c.coorsToXY(e[0],e[1]);e=new x(e[0],
e[1],c.map.spatialReference);f=f.lengths[0];f=1E3>=f?f.toFixed(1)+" m":(f/1E3).toFixed(3)+" km";var g=new B("18px",B.STYLE_NORMAL,B.VARIANT_NORMAL,B.WEIGHT_BOLDER);f=new Y(f,g);f.setHaloColor(new ja(d));f.setHaloSize(2);e=new E(e,f);c.map.graphics.add(e)},function(a){m.publishError(n.getDistanceError,a)})}})};c.drawPolygonAndGetArea=function(a,b){var d=[255,200,0];c.drawGraphic(a,z.POLYGON,function(a){if(a){var f=new ta;f.lengthUnit=e.UNIT_KILOMETER;f.areaUnit=e.UNIT_SQUARE_KILOMETERS;f.polygons=
[a];Z.areasAndLengths(f,function(f){var e=parseFloat(f.areas[0]),g=" km\u00b2";.01<=e?f=e.toFixed(3):(f=(1E6*e).toFixed(1),g=" m\u00b2");b&&"function"==typeof b&&b(e);e=a.getExtent().getCenter();var h=new B("18px",B.STYLE_NORMAL,B.VARIANT_NORMAL,B.WEIGHT_BOLDER);f=new Y(f+g,h);f.setHaloColor(new ja(d));f.setHaloSize(2);f=new E(e,f);c.map.graphics.add(f)},function(a){m.publishError(n.getAreaError,a)})}})};var u=null,K=null,P=null,aa=null,ba,ca=null,da=null,Q=null,ea=null,fa=null,w=null,ra=function(){u&&
u.deactivate();P&&P.deactivate();K=J(K);Q=J(Q);sa()},Na=function(a,b){sa();P=new Ca(c.map);da=a.on("dbl-click",function(a){if(a.graphic)try{W(b.onDrawGraphicDbClick,a.graphic),P.activate(15,a.graphic,{allowAddVertices:"true",allowDeleteVertices:"true",uniformScaling:"true"}),c.map.hideZoomSlider()}catch(f){console.error(f)}});ba=a.on("click",function(a){});aa=c.map.on("click",function(a){P.deactivate();c.map.showZoomSlider()})},sa=function(){aa=J(aa);da=J(da);ba=J(ba)};c.startDrawAndEdit=function(a,
b){var d=k.mixin({},{layerId:"drawAndEditLayerId",onDrawEnd:function(a){},onDrawGraphicClick:function(a){},onDrawGraphicDbClick:function(a){}},b);u=new z(c.map);ra();w=c.getLayerById(d.layerId);w||(w=O({id:d.layerId,type:"draw",index:100}),c.map.addLayer(w));K=u.on("draw-end",function(a){u.deactivate();u=null;c.map.showZoomSlider();switch(a.geometry.type){case "point":if("PICTURE"===ca){fa||(fa=c.getSymbolByObject({type:"esriPMS",url:"images/plot/pic_government.png",contentType:"image/png",color:null,
width:19.5,height:19.5,angle:0,xoffset:0,yoffset:0}));var b=fa}else"TEXT"===ca?(ea||(ea=c.getSymbolByObject({type:"esriTS",text:"\u6587\u5b57"})),b=ea):b=new L;break;case "multipoint":b=new L;break;case "polyline":b=new T;break;default:b=new N}a=new E(a.geometry,b);W(d.onDrawEnd,a);w.add(a);Na(w,d)});ca=a;switch(a){case "DELETE":Q=w.on("click",function(a){w.remove(a.graphic);l.stop(a)});break;case "PICTURE":case "TEXT":a="POINT";default:Q=J(Q),u.activate(z[a])}c.map.hideZoomSlider()};c.clearAllGraphics=
function(){c.map.graphics.clear();w&&w.clear()};c.print=function(a,b){Ma(function(a){var b=document.createElement("a"),c=b.attributes;c.target="_blank";c.href=a.url;b.click()},b)};c.switchBaseMap=function(a){var b=c.getLayerById(a);if(a&&b&&U&&0<U.length){var d=[];r.forEach(U,function(b,c){b.id!==a&&d.push(b.id)},this);r.forEach(d,function(a,b){c.layerVisibleSwitch(a,!1)});c.layerVisibleSwitch(a,!0)}};c.coorsToXY=function(a,b){switch(c.map.spatialReference.wkid){case 102100:case 3857:a=ia.lngLatToXY(a,
b);break;default:a=[a,b]}return a};c.reloadOptionalLayerConfig=function(a){for(var b=null,c=0;c<C.length;c++){var e=C[c];if(e.label===a){b=e;break}}b&&qa(b)};c.subscribe=function(a,b){H[a]?D.subscribe(H[a],b):m.publishError(n.eventNotRegister+a)};c.publish=function(){D.publish.apply(this,arguments)};c.getEventManager=function(){return m};c.layerSetVisibleSwitch=function(a,b){var d=[];r.forEach(C,function(b,c){V(b,function(b,c){b.layerSet&&b.id===a&&d.push(b)})});var e=[];switch(d.length){case 0:m.publishInfo(n.layerSetNotFound);
return;case 1:r.forEach(d,function(a,b){V(a,function(a,b){a.layerSet||e.push(a.id)})});break;default:m.publishInfo(n.repeatIdError);return}r.forEach(e,function(a,d){c.getLayerVisible(a)!==b&&c.layerVisibleSwitch(a,b)})};(function(){console.time(n.apiLoading);var a=p.map;la=a.id;I=a.basemaps;C=a.optionallayers;oa=a.mapOptions;Z=new e(p.services.geometryService?p.services.geometryService:y.geometryService);pa=new Da(p.services.printService?p.services.printService:y.printService);Ka();new Fa({map:c.map,
scalebarUnit:"dual"});console.timeEnd(n.apiLoading)})()};p.apiOptions&&p.apiOptions.mapApiLoaded&&eval(p.apiOptions.mapApiLoaded+"()")})};
