define("dojo/_base/declare dojo/_base/lang dojo/promise/all dojo/dom-construct esri/graphicsUtils esri/tasks/query esri/layers/FeatureLayer esri/symbols/SimpleFillSymbol".split(" "),function(n,k,v,w,p,q,r,t){return n([r],{constructor:function(a,b,c){this.inherited(a,b);this._options=b;this._mapApi=c;this._hightlightSymbol=this._highlightFilterFunc=this._flashFilterFunc=this._flashSymbol=null;this._highlightLineColor=[255,0,255,255];this._highlightFillColor=[115,76,45,100];this._hightlightSymbols=
{simpleMarkerSymbol:{color:this._highlightLineColor,size:10,angle:0,xoffset:0,yoffset:0,type:"esriSMS",style:"esriSMSCircle",outline:{color:this._highlightLineColor,width:0,type:"esriSLS",style:"esriSLSSolid"}},pictureMarkerSymbol:{type:"esriPMS",url:"471E7E31",imageData:"iVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAAAXNSR0IB2cksfwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAMNJREFUSIntlcENwyAMRZ+lSMyQFcI8rJA50jWyQuahKzCDT+6h0EuL1BA1iip8Qg/Ex99fYuCkGv5bKK0EcB40YgSE7bnTxsa58LeOnMd0QhwGXkxB3L0w0IDxPaMqpBFxjLMuaSVmRjurWIcRDHxaiWZuEbRcEhpZpSNhE9O81GiMN5E0ZRt2M0iVjshek8UkTQfZy8JqGHYP/rJhODD4T6wehtbB9zD0MPQwlOphaAxD/uPLK7Z8MB5gFet+WKcJPQDx29XkRhqr/AAAAABJRU5ErkJggg==",
contentType:"image/png",color:null,width:19.5,height:19.5,angle:0,xoffset:0,yoffset:0},simpleLineSymbol:{type:"esriSLS",style:"esriSLSSolid",color:this._highlightLineColor,width:2},simpleFillSymbol:{type:"esriSFS",style:"esriSFSSolid",color:this._highlightFillColor,outline:{type:"esriSLS",style:"esriSLSSolid",color:this._highlightLineColor,width:2}}}},onMouseOver:function(a){this.inherited(arguments);this._showHightlightGraphic(a.graphic)},onMouseOut:function(a){this.inherited(arguments);a.graphic.setSymbol(null)},
onUpdateEnd:function(a){this.inherited(arguments);this._flashFilterFunc&&this._flashFilterFunc(a);this._highlightFilterFunc&&this._highlightFilterFunc(a);this._options.tips&&this._mapApi.setLayerTips(this.id,this._options.tips)},_getHightlightSymbol:function(){return this._hightlightSymbol},_setFlashSymbol:function(a,b){for(var c=0;c<a.length;c++)a[c].setSymbol(b)},_queryTargetGraphic:function(a,b,c){var d=new q;if(c&&"OBJECTID"!==c){for(var f="",g=0;g<a.length;g++)f+="'"+a[g]+"'",g!==a.length-1&&
(f+=",");d.where=c+" in ("+f+")"}else d.objectIds=a;d.outFields=["*"];this.queryFeatures(d,function(a){b&&b(a)},function(a){console.error(a)});return[]},_showHightlightGraphic:function(a){var b="esri.renderer.UniqueValueRenderer"===this.renderer.declaredClass?this._doHightlightSymbol(this.renderer.getSymbol(a)):this._getHightlightSymbol();a.setSymbol(b)},_doFlash:function(a,b,c){var d=this,f=!0,g=d._getHightlightSymbol(),e=setInterval(function(){0<=b?(f?(b--,d._setFlashSymbol(a,g)):d._setFlashSymbol(a,
null),f=!f):(d._flashFilterFunc=null,clearInterval(e),d._setFlashSymbol(a,null))},c)},flash:function(a,b){b=k.mixin({},{center:!1,fieldName:"OBJECTID",delay:300,count:5,scale:2E4},b);var c=b.count,d=b.delay,f=b.fieldName,g=b.scale,e=this,l=dojo.isArray(a)?[].concat(a):[a];e._findGraphicByObjectIds(l,f);e._queryTargetGraphic(l,function(b){try{if(0<b.features.length){var k=p.graphicsExtent(b.features);e._flashFilterFunc=function(){var a=e._findGraphicByObjectIds(l,f);e._doFlash(a,c,d)};!e._map&&e._mapApi&&
(e._map=e._mapApi.map);e._setFitExtent(k,g)}else if(e._mapApi){var h=e._mapApi,m=h.getEventManager();m.publishInfo(h.Strings.featureNotFound+f+"="+a)}}catch(u){e._mapApi&&(h=e._mapApi,m=h.getEventManager(),m.publishError(h.Strings.queryError,u))}},f)},_findGraphicByObjectIds:function(a,b){b=b||"OBJECTID";for(var c=[],d=0;d<this.graphics.length;d++)for(var f=this.graphics[d],g=0;g<a.length;g++)f.attributes[b]==a[g]&&c.push(f);return c},setFlashSymbol:function(a){this._flashSymbol=a},_setFitExtent:function(a,
b){var c=this;c.minScale&&c._map.getScale()>=c.minScale?c._map.setScale(c.minScale).then(function(){c._map.setExtent(a)}):a.xmin==a.xmax&&a.ymin==a.ymax?c._mapApi.centerAt(a.xmin,a.ymin).then(function(){c._map.setScale(b)}):c._map.setExtent(a)},_setMap:function(a,b){var c=this.inherited(arguments);this._setLayerDefaultHightlightSymbol();return c},_setLayerDefaultHightlightSymbol:function(){this._hightlightSymbol=this._doHightlightSymbol(this.renderer.defaultSymbol?this.renderer.defaultSymbol:this.renderer.symbol)},
_doHightlightSymbol:function(a){var b=k.clone(a);switch(a.type){case "simplemarkersymbol":b.setSize(a.size+2);break;case "picturemarkersymbol":b.setHeight(1.5*a.height);b.setWidth(1.5*a.width);break;case "simplelinesymbol":obj=this._hightlightSymbols.simpleLineSymbol;b.setWidth(a.width+3);b.setColor(obj.color);b.setStyle(obj.style);break;case "picturefillsymbol":case "simplefillsymbol":b=new t(this._hightlightSymbols.simpleFillSymbol),b.outline.setWidth(a.outline.width+3)}return b}})});
