var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,c){return c})}},"es8","es3");
define("dojo/_base/declare dojo/on dojo/_base/lang esri/geometry/Polyline esri/SpatialReference esri/InfoTemplate esri/layers/GraphicsLayer esri/tasks/query esri/tasks/QueryTask esri/graphic esri/Color esri/renderers/UniqueValueRenderer esri/renderers/SimpleRenderer esri/symbols/SimpleLineSymbol".split(" "),function(a,b,c,d,e,k,l,m,n,p,q,r,t,f){return a([l],{constructor:function(a){this._options=a;a=c.mixin({},{infoTemplate:!0,field:"Name",type:"simple",defaultSymbol:{type:"esriSLS",style:"esriSLSSolid",
color:[255,0,0,255],width:2},values:[{value:"\u5e72\u7ebf",color:[255,0,0,1]},{value:"",color:[255,0,255,1]}]},a.renderer);this._defaultHightLineSymbol=new f({color:[255,0,255,255],width:3});a.infoTemplate&&(this.infoTemplate=new k("\u7ba1\u7ebf\u57fa\u672c\u4fe1\u606f","<label>\u7ebf\u8def\uff1a</label><label>${"+a.field+"}</label>"));var b=new f(a.defaultSymbol);switch(a.type){case "unique":b=new r(b,a.field);for(var d=0;d<a.values.length;d++){var h=a.values[d];b.addValue(h.value,(new f({width:2})).setColor(new q(h.color)))}break;
default:b=new t(b)}this.renderer=b},onGraphicAdd:function(a){},onMouseOver:function(a){a=a.graphic;a.symbol=this._defaultHightLineSymbol;a.draw()},onMouseOut:function(a){a=a.graphic;a.symbol=null;a.draw()},_requestData:function(){var a=this,b=new n(a._params.url),c=new m;c.returnGeometry=!0;c.outFields=["*"];c.where="1=1";b.execute(c,function(b){b=b.features;for(var c=b.length,e=0;e<c;e++){var f=b[e],g=new d(f.geometry);g=new p(g);g.setAttributes(f.attributes);a.add(g)}},function(a){console.error("\u52a0\u8f7d\u7ba1\u7ebf\u6570\u636e\u51fa\u9519\uff01");
console.error(a)})},_setMap:function(a,b){var c=this.inherited(arguments);this._requestData();return c}})});
